const { loadModule, assert, equal, done } = require("./helpers")
const C = loadModule("Coordinator.js")
function setup() {
  const calls = [], reads = [], events = [], notices = [], errors = [], refreshes = []
  const backend = { patchTicket(id, patch, cb) { calls.push({id, patch, cb}) }, getTicket(id, cb) { reads.push({id, cb}) } }
  const c = C.create({ backend, changed() {}, apply(t) { events.push(t) }, confirm(s) { notices.push(s) }, error(s) { errors.push(s) }, refresh() { refreshes.push(c.beginRead()) } })
  return { c, calls, reads, events, notices, errors, refreshes }
}
const ticket = { Id: "a", Number: 123, Title: "Printer", Status: {Id: 1, Name: "Open"} }
const closed = { Id: 5, Name: "Closed" }
const h = setup()
assert(h.c.setStatus(ticket, closed, "Tech"), "accept a status change")
equal(h.c.pending("a"), "Closing…", "pending belongs to ticket identity")
assert(!h.c.setStatus(ticket, closed, "Tech"), "repeated selection blocked")
equal(h.calls.length, 1, "only one external write")
h.calls[0].cb({ ok: true })
equal(h.events[0].Status.Name, "Closed", "successful PATCH updates locally before another fetch")
equal(h.c.pending("a"), "", "pending clears")
equal(h.notices, ["Ticket #123 closed"], "confirmation once")
h.calls[0].cb({ ok: true })
equal(h.notices.length, 1, "duplicate callback never confirms twice")
const failure = setup()
failure.c.setStatus(ticket, closed, "Tech")
failure.calls[0].cb(ApiError())
function ApiError() { return { ok: false, kind: "api", status: 400, error: "New cannot be selected manually." } }
equal(failure.events, [], "failed PATCH leaves last confirmed record untouched")
equal(failure.c.pending("a"), "", "failure clears pending")
equal(failure.notices, [], "failure never confirms")
assert(failure.errors[0].includes("New cannot be selected manually."), "server Notifications error remains actionable")
const reason = setup()
assert(!reason.c.setStatus(ticket, {Id: 6, Name: "Escalated", AskForReason: true}, "Tech"), "reason-required selection refused")
equal(reason.calls.length, 0, "reason-required status never writes")
assert(reason.errors[0].includes("Open in Gorelo"), "reason limitation offers UI handoff")
equal(reason.c.pending("a"), "", "confirmed dropdown can remain unchanged")
const life = setup()
const oldRead = life.c.beginRead()
life.c.setStatus(ticket, closed, "Tech")
assert(!life.c.validRead(oldRead), "pre-mutation poll/search rejected")
const duringRead = life.c.beginRead()
assert(!life.c.validRead(duringRead), "poll during mutation cannot replace confirmed row")
life.calls[0].cb({ok:true})
assert(!life.c.validRead(duringRead), "response started before success cannot reintroduce stale row")
assert(life.c.validRead(life.c.beginRead()), "fresh authoritative read accepted")
const switched = setup()
switched.c.setStatus(ticket, closed, "Tech")
switched.c.reset()
switched.calls[0].cb({ok:true})
equal([switched.events, switched.notices, switched.c.pending("a")], [[], [], ""], "connection switch clears pending and stale callbacks do nothing")
const timeout = setup()
timeout.c.setStatus(ticket, closed, "Tech")
timeout.calls[0].cb({ok:false, kind:"network", error:"Request timed out"})
equal(timeout.c.pending("a"), "Checking status…", "ambiguous network result reads before retry")
equal(timeout.calls.length, 1, "timeout never blindly resubmits")
timeout.reads[0].cb({ok:true, data:{...ticket, Status:closed}})
equal(timeout.events[0].Status.Id, 5, "authoritative read resolves timeout")
equal(timeout.notices, ["Ticket #123 closed"], "read-confirmed change confirms once")
const unknown = setup()
unknown.c.setStatus(ticket, closed, "Tech")
unknown.calls[0].cb({ok:false, kind:"network", error:"timeout"})
unknown.reads[0].cb({ok:false, error:"offline"})
equal(unknown.c.pending("a"), "", "read failure clears visual pending")
assert(!unknown.c.setStatus(ticket, closed, "Tech"), "unresolved result reconciles rather than blindly retrying")
equal(unknown.calls.length, 1, "unresolved change has no second PATCH")
assert(unknown.errors[0].includes("could not be confirmed"), "timeout never claims rejection")
const malformed = setup()
malformed.c.setStatus(ticket, closed, "Tech")
malformed.calls[0].cb({ok:false,kind:"network",error:"timeout"})
malformed.reads[0].cb({ok:true,data:{Id:"wrong-ticket",Status:closed}})
equal(malformed.events, [], "malformed detail cannot mutate another ticket")
equal(malformed.notices, [], "wrong ticket detail never confirms a write")
const callback = setup(), outcomes=[]
callback.c.setStatus(ticket, closed, "Tech", (ok,message)=>outcomes.push({ok,message}))
callback.calls[0].cb({ok:true})
equal(outcomes,[{ok:true,message:""}],"optional status completion callback preserved")
const concurrent=setup(), second={...ticket,Id:"b",Number:124}
concurrent.c.setStatus(ticket,closed,"Tech")
concurrent.c.setStatus(second,{Id:3,Name:"On Hold"},"Tech")
equal([concurrent.c.pending("a"),concurrent.c.pending("b")],["Closing…","Saving…"],"simultaneous writes have independent pending state")
concurrent.calls[0].cb({ok:true})
assert(!concurrent.c.validRead(concurrent.refreshes[0]),"first completion refresh rejected while another ticket write remains pending")
equal(concurrent.c.pending("b"),"Saving…","first completion cannot clear another ticket pending state")
concurrent.calls[1].cb({ok:true})
assert(!concurrent.c.validRead(concurrent.refreshes[0]),"earlier completion refresh stays stale after second write settles")
assert(concurrent.c.validRead(concurrent.refreshes[1]),"last completion starts valid authoritative refresh")
equal(concurrent.events.map(t=>[t.Id,t.Status.Name]),[["a","Closed"],["b","On Hold"]],"both concurrent writes settle with own statuses")
equal(concurrent.notices,["Ticket #123 closed","Ticket #124 changed to On Hold"],"each concurrent mutation confirms exactly once")
const resetRead=setup(), completedAfterReset=[]
resetRead.c.setStatus(ticket,closed,"Tech",(ok)=>completedAfterReset.push(ok))
resetRead.calls[0].cb({ok:false,kind:"network",error:"timeout"})
equal(resetRead.c.pending("a"),"Checking status…","confirming read starts after ambiguous write")
resetRead.c.reset()
resetRead.reads[0].cb({ok:true,data:{...ticket,Status:closed}})
equal([resetRead.events,resetRead.notices,resetRead.errors,resetRead.refreshes,completedAfterReset,resetRead.c.pending("a")],[[],[],[],[],[],""],"reset during confirming read suppresses all stale mutation effects")
const serverFailure=setup()
serverFailure.c.setStatus(ticket,closed,"Tech")
serverFailure.calls[0].cb({ok:false,kind:"api",status:503,error:"Unavailable"})
equal([serverFailure.calls.length,serverFailure.reads.length,serverFailure.c.pending("a")],[1,1,"Checking status…"],"5xx triggers an authoritative read instead of retrying PATCH")
serverFailure.reads[0].cb({ok:true,data:{...ticket,Status:closed}})
equal(serverFailure.notices,["Ticket #123 closed"],"5xx followed by confirmed detail can still confirm successful change")
equal(serverFailure.calls.length,1,"5xx reconciliation never blindly resubmits")
done("test_coordinator")
